os: linux
dist: bionic
services:
  - docker
language: python
python:
  - "3.7"
cache:
  pip: true
addons:
  apt:
    update: true
    packages:
      - openvswitch-switch
install:
  - set -e
  - bin/setup_daq
script:
  - set -e
  - bin/test_daq
env:
  global:
    - DOCKER_STARTUP_TIMEOUT_MS=60000
  jobs:
    - DAQ_TEST=aux SHARD=0
    - DAQ_TEST=aux SHARD=1
    - DAQ_TEST=aux SHARD=2
    - DAQ_TEST=aux SHARD=3
    - DAQ_TEST=aux SHARD=4
    - DAQ_TEST=aux SHARD=5
    - DAQ_TEST=aux SHARD=6
    - DAQ_TEST=aux SHARD=7
    - DAQ_TEST=aux SHARD=8
    - DAQ_TEST=aux SHARD=9
    - DAQ_TEST=aux SHARD=10
    - DAQ_TEST=aux SHARD=11
